name: Deploy Vue to Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descargar repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4️⃣ Ejecutar TESTS (si fallan → se corta todo)
      - name: Run unit tests
        run: npm run test -- --run

      # 5️⃣ Build (solo si los tests pasan)
      - name: Build Vue
        run: npm run build

      # 6️⃣ Configurar SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo -e "Host *\n  StrictHostKeyChecking no\n  IdentitiesOnly yes" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      # 7️⃣ Limpiar carpeta remota
      - name: Clean dist folder on server
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "rm -rf /var/www/alumnos/${{ secrets.USERNAME }}/dist/*"

      # 8️⃣ Deploy
      - name: Deploy dist via SCP
        run: |
          scp -r dist/* \
          ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/alumnos/${{ secrets.USERNAME }}/dist/


# name: Deploy HTML to Server


# on:
#   push:
#     branches: ["main",]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest


#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4


#       - name: Setup SSH
#         run: |
#           mkdir -p ~/.ssh
#           echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
#           chmod 600 ~/.ssh/id_ed25519
#           echo -e "Host *\n  StrictHostKeyChecking no\n  IdentitiesOnly yes" > ~/.ssh/config
#           chmod 600 ~/.ssh/config




#       - name: Deploy via SCP
#         run: |
#           ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "rm -rf /var/www/alumnos/${{ secrets.USERNAME }}/*"
#           scp -o StrictHostKeyChecking=no -r ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/alumnos/${{ secrets.USERNAME }}/
